### ISSUE TITLE
Crash in EnemyAI.think()

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/dark-world#3]
```
Exception in callback EnemyAI.think()
handle: <TimerHandle when=15530281.037834777 EnemyAI.think()>
Traceback (most recent call last):
  File "dist/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/mauve/dev/dark-world/darkworld/ai.py", line 88, in think
    d = direction_to(e.pos, step)
  File "/home/mauve/dev/dark-world/darkworld/coords.py", line 75, in direction_to
    return INV_DIRECTION_MAP[delta]
KeyError: (0, 0)
```

**Comment by lordmauve** [comment]
NB. This is seen with various keys including `(0, 0)` and `(0, -2)`.
